cols_categorical = [
    'ACCOMP', 'CODE_ARRIVEE', 'CIMU', 'ATTENTE', 'CIRCONSTANCES', 'GLUCOSE', 'C_CETO', 'FAMILLE',
    'LEUCOCYTES', 'NITRITES', 'PREMIER_MOTIF',
    'SANG', 'PROTIDES', 'SEXE', 'HOSPITALISATION'
]

cols_numerical = [
    'AGE', 'CETONEMIE', 'DOULEUR', 
    'FC', 'GLYCEMIE', 'HEMOCUE', 'HEURE_ARRIVEE', 'JOUR_SEMAINE',
    'MOIS', 'OH', 'OXYGENE', 'PAD', 'PAS',
    'SATURATION', 'SEMAINE_ANNEE', 'TEMPERATURE'
]

target = 'HOSPITALISATION'
